Add missing include of stdlib.h for exit() prototype.
This should fix the following compilation error seen on riscv64:

/<<PKGBUILDDIR>>/hwy/targets.cc:205:3: error: ‘exit’ was not declared in this scope
  205 |   exit(1);  // trap/abort just freeze Spike
      |   ^~~~
/<<PKGBUILDDIR>>/hwy/targets.cc:209:1: error: ‘noreturn’ function does return [-Werror]