Make sure to link targets_test against GCC/atomic lib
This commit will fix the following compilation error on armel:

/usr/bin/ld: CMakeFiles/targets_test.dir/hwy/targets_test.cc.o: undefined reference to symbol '__atomic_store_8@@LIBATOMIC_1.0'
/usr/bin/ld: /usr/lib/arm-linux-gnueabi/libatomic.so.1: error adding symbols: DSO missing from command line

The keyword PRIVATE needs to be kept in sync in all
target_link_libraries calls.

Some minor CMake comments shuffling to make sections symetrics.